services:
  backend:
    image: vortex.kronshtadt.ru:8443/maas-hosted/maas-backend:v3
    #build:
    #  context: .
    #  args:
    #    - LINUX_PROXY_URL=${LINUX_PROXY_URL}
    container_name: backend
    environment:
      - CORS_ORIGINS=["*"]
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_ALLOW_METHODS=["*"]
      - CORS_ALLOW_HEADERS=["*"]
      - LINUX_PROXY_URL=${LINUX_PROXY_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - maas-internal
      #- maas-backend-stl_backend-network
      - traefik-global-proxy
    labels:
    #   # Enable Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-global-proxy"

    #   # Router configuration (update domain as needed)
    #  - "traefik.http.routers.lk-api-int.rule=Host(`maas.int.kronshtadt.ru`) && PathPrefix(`/api/v3/`)"
      - "traefik.http.routers.lk-api-int.rule=Host(`10.33.42.18`) && PathPrefix(`/api/v3/`)"
#      - "traefik.http.routers.lk-api-int.rule=Host(`maas.aeromax-group.ru`) && PathPrefix(`/api/v3/`)"
      - "traefik.http.routers.lk-api-int.entrypoints=https"
      - "traefik.http.routers.lk-api-int.tls=true"
      - "traefik.http.routers.lk-api-int.middlewares=strip-api-prefix@docker,cors@file"

#      - "traefik.http.routers.lk-api-pub.rule=Host(`maas.aeromax-group.ru`) && PathPrefix(`/api/v3/`)"
#      - "traefik.http.routers.lk-api-pub.entrypoints=https"
#      - "traefik.http.routers.lk-api-pub.tls=true"
#      - "traefik.http.routers.lk-api-pub.middlewares=strip-api-prefix@docker"


      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api/v3/"

    #   # Service configuration
      - "traefik.http.services.lk-api.loadbalancer.server.port=8000"
      - "traefik.http.services.lk-api.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.lk-api.loadbalancer.healthcheck.interval=30s"

    #   # Security headers middleware
    #   - "traefik.http.middlewares.lk-api-headers.headers.customresponseheaders.X-Frame-Options=DENY"
    #   - "traefik.http.middlewares.lk-api-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
    #   - "traefik.http.middlewares.lk-api-headers.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
    #   - "traefik.http.middlewares.lk-api-headers.headers.customresponseheaders.Strict-Transport-Security=max-age=31536000; includeSubDomains"

    #   # Apply middleware
    #   - "traefik.http.routers.lk-api.middlewares=lk-api-headers"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs

networks:
  maas-internal:
    external: true
  #maas-backend-stl_backend-network:
  traefik-global-proxy:
    external: true

volumes:
  uploads:
  logs:
  data:
  main:
